;;; ox-cv-silver.el --- Org export backend mimicking silver-dev-cv -*- lexical-binding: t; -*-

;; Exports an org file to a LaTeX CV styled like the typst silver-dev-cv
;; template.  Headlines are dispatched on their tags:
;;   :job:        -> \cvjob, using INSTITUTION/LOCATION/DATE properties
;;   :oneline:    -> \cvskill
;;   :education:  -> \cveducation, using MAJOR/DATE/LOCATION properties
;;   :descript:   -> \cvsection + \cvdescript (body text)
;;   level-1 else -> \cvsection (container; children render themselves)
;;
;; Per-application tailoring works at the bullet level.  Mark a list item
;; with an export snippet naming the variants it belongs to, e.g.
;;   - Built a budget optimization system. @@cv:kraken,uber@@
;; When `org-cv-silver-active-variant' is set, items carrying a cv snippet
;; are kept only if that variant is listed.  Items with no cv snippet are
;; always kept (shared content).  The snippet itself never reaches output.

;;; Code:

(require 'ox-latex)
(require 'cl-lib)

;;;; Bullet-level filtering

(defvar org-cv-silver-active-variant nil
  "Variant name selecting which tagged bullets to keep, or nil for all.")

(defun org-cv-silver--item-variants (item)
  "Return the list of cv variant strings tagged on ITEM, or nil if none."
  (let (vs)
    (org-element-map item 'export-snippet
      (lambda (s)
        (when (string= (org-element-property :back-end s) "cv")
          (setq vs (append vs (split-string
                               (org-element-property :value s) "," t "[ \t]*")))))
      nil nil 'plain-list)
    vs))

(defun org-cv-silver-filter-parse-tree (tree _backend _info)
  "Drop list items whose cv variant set excludes the active variant."
  (when org-cv-silver-active-variant
    (org-element-map tree 'item
      (lambda (item)
        (let ((vs (org-cv-silver--item-variants item)))
          (when (and vs (not (member org-cv-silver-active-variant vs)))
            (org-element-extract-element item))))))
  tree)

;;;; Helpers

(defun org-cv-silver--latexify (s)
  "Convert org snippet string S (a property value) to a LaTeX string."
  (when (and s (not (string-empty-p s)))
    (string-trim (org-export-string-as s 'latex t '(:with-toc nil)))))

;;;; Transcoders

(defun org-cv-silver-headline (headline contents info)
  "Transcode a HEADLINE element into the matching CV macro."
  (let* ((tags (org-element-property :tags headline))
         (title (org-export-data (org-element-property :title headline) info))
         (level (org-export-get-relative-level headline info))
         (contents (or contents "")))
    (cond
     ((member "job" tags)
      (format "\\cvjob{%s}{%s}{%s}{%s}{%s}\n"
              title
              (or (org-cv-silver--latexify
                   (org-element-property :INSTITUTION headline)) "")
              (or (org-element-property :LOCATION headline) "")
              (or (org-element-property :DATE headline) "")
              contents))
     ((member "oneline" tags)
      (format "\\cvskill{%s}{%s}\n" title (string-trim contents)))
     ((member "education" tags)
      (let* ((loc (org-element-property :LOCATION headline))
             (inst (if (and loc (not (string-empty-p loc)))
                       (concat title ", " loc)
                     title)))
        (format "\\cveducation{%s}{%s}{%s}{}\n"
                inst
                (or (org-cv-silver--latexify
                     (org-element-property :MAJOR headline)) "")
                (or (org-element-property :DATE headline) ""))))
     ((member "descript" tags)
      (format "\\cvsection{%s}\n\\cvdescript{%s}\n\\sectionsep\n"
              title (string-trim contents)))
     ((= level 1)
      (format "\\cvsection{%s}\n%s\\sectionsep\n" title contents))
     (t contents))))

(defun org-cv-silver-inner-template (contents _info)
  "Return body CONTENTS with no table of contents or bibliography."
  contents)

(defun org-cv-silver-template (contents info)
  "Wrap body CONTENTS in a full document using the cv-silver style."
  (let ((name (or (plist-get info :cv-name) ""))
        (address (or (plist-get info :cv-address) ""))
        (email (or (plist-get info :cv-email) ""))
        (github (or (plist-get info :cv-github) ""))
        (date (or (plist-get info :cv-date) "")))
    (concat
     "% Generated by ox-cv-silver. Compile with lualatex.\n"
     "\\documentclass[11pt]{article}\n"
     "\\usepackage{cv-silver}\n"
     (format "\\newcommand{\\cvname}{%s}\n" name)
     (format "\\newcommand{\\cvdate}{%s}\n" date)
     (format "\\hypersetup{pdfauthor={%s},pdftitle={%s - Resume}}\n" name name)
     "\\begin{document}\n"
     (format "\\cvheader{%s}{%s}{%s}{%s}\n" name address email github)
     contents
     "\\end{document}\n")))

;;;; Backend definition

(org-export-define-derived-backend 'cv-silver 'latex
  :options-alist
  '((:cv-name "CV_NAME" nil nil t)
    (:cv-address "CV_ADDRESS" nil nil t)
    (:cv-date "CV_DATE" nil nil t)
    (:cv-email "CV_EMAIL" nil nil t)
    (:cv-github "CV_GITHUB" nil nil t)
    (:cv-font "CV_FONT" nil "Iosevka" t))
  :filters-alist
  '((:filter-parse-tree . org-cv-silver-filter-parse-tree))
  :translate-alist
  '((template . org-cv-silver-template)
    (inner-template . org-cv-silver-inner-template)
    (headline . org-cv-silver-headline))
  :menu-entry
  '(?v "Export to silver CV"
       ((?L "As LaTeX buffer" org-cv-silver-export-as-latex)
        (?l "As LaTeX file" org-cv-silver-export-to-latex)
        (?p "As PDF file" org-cv-silver-export-to-pdf))))

;;;; Export commands

(defun org-cv-silver--pdf-process ()
  "Two lualatex passes (needed for lastpage page totals)."
  '("lualatex -interaction nonstopmode -output-directory %o %f"
    "lualatex -interaction nonstopmode -output-directory %o %f"))

(defun org-cv-silver--compile (texfile)
  "Compile TEXFILE with lualatex (two passes).
The only cross-reference in a CV is LastPage (the footer page total),
which is undefined on the first pass and resolved on the second.  org
scans both passes' output, so it would otherwise flag that benign
first-pass warning; drop only that category here."
  (let ((org-latex-pdf-process (org-cv-silver--pdf-process))
        (org-latex-known-warnings
         (cl-remove-if (lambda (e) (equal (cdr e) "[undefined reference]"))
                       org-latex-known-warnings)))
    (org-latex-compile texfile)))

(defun org-cv-silver-export-as-latex (&optional async subtree visible body)
  "Export current buffer to a cv-silver LaTeX buffer."
  (interactive)
  (org-export-to-buffer 'cv-silver "*Org CV-SILVER Export*"
    async subtree visible body))

(defun org-cv-silver-export-to-latex (&optional async subtree visible body)
  "Export current buffer to a cv-silver LaTeX file."
  (interactive)
  (let ((file (org-export-output-file-name ".tex" subtree)))
    (org-export-to-file 'cv-silver file async subtree visible body)))

(defun org-cv-silver-export-to-pdf (&optional async subtree visible body)
  "Export current buffer to a cv-silver PDF via lualatex."
  (interactive)
  (let ((file (org-export-output-file-name ".tex" subtree)))
    (org-export-to-file 'cv-silver file async subtree visible body nil
      #'org-cv-silver--compile)))

(defun pv/cv-export (variant)
  "Export the current buffer to pv-cv-VARIANT.pdf keeping VARIANT bullets.
With an empty VARIANT, export the full CV to pv-cv-full.pdf."
  (interactive "sVariant (blank for full CV): ")
  (let* ((variant (string-trim variant))
         (org-cv-silver-active-variant (unless (string-empty-p variant) variant))
         (base (if (string-empty-p variant) "full" variant))
         (file (expand-file-name (format "pv-cv-%s.tex" base))))
    (org-export-to-file 'cv-silver file nil nil nil nil nil #'org-cv-silver--compile)))

(provide 'ox-cv-silver)
;;; ox-cv-silver.el ends here
